### ISSUE TITLE
Shifted outer borders

### ISSUE THREAD

**Issue by EysseW** [roidm/sway-borders#1]
So I am fiddling around with shadows ATM, but I wanna shift them. A might be stupid, but I am pretty sure there is no way to shift them, like actual shadows probably would. I would like to see this added.

**Comment by roidm** [comment]
i'm not the developer of sway-borders , go to [https://github.com/fluix-dev/sway-borders](url) and make a feature request

**Comment by EysseW** [comment]
right. Please delete your fork if it doesn't add anything.

**Comment by EysseW** [comment]
lol nevermind it's a dotfiles repository. Please name it better tho.
